### ISSUE TITLE
Missleading icon 

### ISSUE THREAD

**Issue by RafaelCz** [GijsGoudzwaard/Image-Optimizer#10]
The icon you are using in the drop area (arrow pointing to a cloud) may create the impression that this app is using an online service to compress the files.
Since this isn't the case, I'd suggest you choose an appropriate icon.

Beside that this icon looks like it's straight out of an iPhone/Mac app, it doesn't really fit the [HIG of elementary OS](https://elementary.io/de/docs/human-interface-guidelines#human-interface-guidelines) ;)

**Comment by GijsGoudzwaard** [comment]
You are right, the current icon does create the impression of uploading to a cloud.

**Comment by yeboahnanaosei** [comment]
Yeah bro. I will recommend you read the [Human Interface Guidelines of elementary OS](https://elementary.io/docs/human-interface-guidelines#human-interface-guidelines). that is if you have not already done that

**Comment by TraumaD** [comment]
I would love to help out if you'd have it. I have threw together a icon if it looks good to you I'll send a PR.
![upload-icon](https://user-images.githubusercontent.com/10608836/31051033-6de48ffc-a623-11e7-949d-b759798e4936.png)

**Comment by TraumaD** [comment]
Here's what it looks like in app.
![screenshot from 2017-09-30 21 58 25](https://user-images.githubusercontent.com/10608836/31051297-818301ea-a62a-11e7-85ab-da3c021025ea.png)

**Comment by yeboahnanaosei** [comment]
Guy, can we get rid of the arrow. I feel it is the arrow that is causing the problem. The arrow makes it feel like you would upload the file. I imagine something like this would be cool:

<img width="1138" alt="op" src="https://user-images.githubusercontent.com/22800157/31051629-71a2b0fe-a65c-11e7-8872-cd74a1e33eb2.png">

**Comment by TraumaD** [comment]
The arrow shows you need action. You need to put a image into the app for it to do something. If you didn't have any words and all you saw was the image you should still be able to figure out what to do. I feel like without the arrow an image of a picture could mean anything (like the app is loading and this is a splash img, or that it will display pictures here, ect.)

**Comment by yeboahnanaosei** [comment]
I understand you perfectly. But in keeping with [elementary's HIG,](https://elementary.io/docs/human-interface-guidelines#human-interface-guidelines) I thought it would help make the app feel more consistent and even more native if you just had an icon and few words instructing the user on what to do. And here is the case we already know what the app does before even installing. Take a look at these apps by elementary 

![screenshot from 2017-10-01 04-09-49](https://user-images.githubusercontent.com/22800157/31051678-686c2e8c-a65e-11e7-9277-19503bd10923.png)


![screenshot from 2017-10-01 04-11-56](https://user-images.githubusercontent.com/22800157/31051692-b745f182-a65e-11e7-8fce-75fd26e016bd.png)

**Comment by TraumaD** [comment]
All the icons here have action parts though like pluses and arrows except the folder icons. Maybe instead of an arrow it would be better to use a "+" or something? Or maybe instead it should use the built-in "insert-image" icon?

Built-In icon
![insert-image](https://user-images.githubusercontent.com/10608836/31051731-0df12188-a636-11e7-8555-df188c72e756.png)

Example screenshot:
![screenshot from 2017-09-30 21 58 25](https://user-images.githubusercontent.com/10608836/31051745-70245aaa-a636-11e7-8aa3-6854cf4e93b1.png)

**Comment by yeboahnanaosei** [comment]
No problem. The only issue I personally have is with the arrow. That's all

**Comment by TraumaD** [comment]
The more I think on it the more I really think we should be using the <a href="https://github.com/elementary/icons/blob/master/actions/64/insert-image.svg" target="blank">built-in action icon</a> for this. That is one less custom icon that has to be shipped. And not that this is meant to be used with other icon themes doing so would mean that the icon would adapt to a that theme change.

**Comment by GijsGoudzwaard** [comment]
While that would be a good alternative, I don't really think that that icons fits the theme of this app. An alternative to the current icon could be just a '+' in purple.

**Comment by TraumaD** [comment]
Hows this?
![upload_icon](https://user-images.githubusercontent.com/10608836/31285983-6c2e9f8c-aa82-11e7-953e-6909b695d9bd.png)

![screenshot from 2017-10-06 10 39 03](https://user-images.githubusercontent.com/10608836/31286051-9a15bcf0-aa82-11e7-870f-060e27a3422d.png)

**Comment by TraumaD** [comment]
I also tried keeping the green plus and instead giving it the same picture as the app icon.
![screenshot from 2017-10-06 10 13 25](https://user-images.githubusercontent.com/10608836/31286178-f7a5af74-aa82-11e7-9976-250454ab0290.png)

**Comment by GijsGoudzwaard** [comment]
I quite like the second icon (with the green +). Could you create a pull request that changes the upload icon?

**Comment by TraumaD** [comment]
Will do as soon as I get back to my computer.
