### ISSUE TITLE
App icon could more closely match elementary HIG

### ISSUE THREAD

**Issue by alexgleason** [GijsGoudzwaard/Image-Optimizer#12]
Looks like the app icon is currently inspired by Material Design. I like it, but with a few tweaks in reference to the [elementary HIG for icons](https://elementary.io/docs/human-interface-guidelines#iconography) it could more closely match the other icons in the set.

Using more color contrast, and maybe putting a highlight on the top of the icon to give it depth would likely be enough.

**Comment by GijsGoudzwaard** [comment]
I agree that this would be better, however I am terrible at creating icons. Any help on this issue would be much appreciated.

**Comment by TraumaD** [comment]
I would love to help out if you'd have it. I have threw together a icon if it looks good to you I'll send a PR.
![com github image-optimizer](https://user-images.githubusercontent.com/10608836/31051044-8cee568a-a623-11e7-9d92-25f34518341a.png)

**Comment by alexgleason** [comment]
This is a great improvement, though I'm wondering if it too closely resembles the generic photo icons in eOS.

I bet if you made the photos blue instead of red it would set the icon apart sufficiently.

**Comment by TraumaD** [comment]
Is this better?

![com github image-optimizer-alt](https://user-images.githubusercontent.com/10608836/31051110-6c897724-a625-11e7-87fe-7a5ba05893c4.png)

**Comment by alexgleason** [comment]
This is my choice, personally. Nice work!

**Comment by TraumaD** [comment]
I'll fix'em up and send a PR.
