### ISSUE TITLE
could you make a flatpak for Image-Optimizer?

### ISSUE THREAD

**Issue by chemel9** [GijsGoudzwaard/Image-Optimizer#23]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for Image-Optimizer?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by GijsGoudzwaard** [comment]
Thanks for the request, I'll look into it.

**Comment by bilelmoussaoui** [comment]
Need any help with this?

**Comment by GijsGoudzwaard** [comment]
That'd be great. :+1:

**Comment by bilelmoussaoui** [comment]
Done https://github.com/flathub/flathub/pull/526

**Comment by bilelmoussaoui** [comment]
On flathub https://flathub.org/apps/details/com.github.gijsgoudzwaard.image-optimizer. Can be closed now

**Comment by GijsGoudzwaard** [comment]
@bilelmoussaoui When there is an update how would I update the flatpak? Or does it automatically detect a release?

**Comment by bilelmoussaoui** [comment]
Just update this file https://github.com/flathub/com.github.gijsgoudzwaard.image-optimizer/blob/master/com.github.gijsgoudzwaard.image-optimizer.json, the url and sha256 should be updated for the `image-resizer` module.
