### ISSUE TITLE
Optimizing PNG images doesn't work

### ISSUE THREAD

**Issue by NathanBnm** [GijsGoudzwaard/Image-Optimizer#37]
The loader is just infinite spinning and nothing happen.

**Comment by GijsGoudzwaard** [comment]
OptiPNG takes quite a while to optimize the images. Are you sure that it doesn't just take long? Let it spin for a couple of minutes, depending on how big the images are.

**Comment by NathanBnm** [comment]
I'm going to try again, I'll tell you if it doesn't work

**Comment by NathanBnm** [comment]
Maybe you should think to add more indications in app, when it's finished, in progress...

**Comment by NathanBnm** [comment]
@GijsGoudzwaard Actually this is really not working

**Comment by GijsGoudzwaard** [comment]
I've tested this and it works on my machine. If you run Image optimizer through the terminal, does it show errors? Also what is the file name? Maybe it has a special character in it that breaks image optimizer.

**Comment by NathanBnm** [comment]
There is no errors in the Terminal, and no special characters in file name. I'm going to try with other files.

Actually this is working well with JPG files, but I left it loading like 30min with a PNG file ans it didn't do anything.

**Comment by GijsGoudzwaard** [comment]
It shouldn't be taking 30 minutes. Could you upload the png that doesn't work so I can test it?

**Comment by NathanBnm** [comment]
I guess not XD I will as soon as possible

**Comment by NathanBnm** [comment]
I tried with other files and this is working. don't know why the files which ones I tried weren't working
