### ISSUE TITLE
How can I translate 'Optimize image'?

### ISSUE THREAD

**Issue by michalzkosmosu** [GijsGoudzwaard/Image-Optimizer#42]
How can I translate 'Optimize image' from context menu into Polish?
![](https://i.postimg.cc/Gp6kLbP8/optimize-resize.gif)

**Comment by GijsGoudzwaard** [comment]
Not sure how that would work. It is defined in a config file here https://github.com/GijsGoudzwaard/Image-Optimizer/blob/master/data/com.github.gijsgoudzwaard.image-optimizer.contract

I'm not sure how that text could be translated.
