### ISSUE TITLE
Allow optimizing multiple image from Files

### ISSUE THREAD

**Issue by wout** [GijsGoudzwaard/Image-Optimizer#49]
Currently, when you select multiple images in Files and use the contextual menu to optimize them, only the active image is added to the queue. It would be great to have them all added.

**Comment by GijsGoudzwaard** [comment]
When selecting multiple files it should optimize them all. On what system are you using Image Optimizer and what version?

**Comment by wout** [comment]
Thanks for your quick reply. That's odd, I'm using elementary OS:

![image](https://user-images.githubusercontent.com/107324/89731217-25303d00-da3d-11ea-93b2-a11d5f9c0e3a.png)

I update regularly, so I think Image Optimizer is at the latest release (`0.1.17`?).

These are the steps I'm following:

- select multiple PNG's in Files
- select Optimize image from the contextual menu

Image Optimizer image opens with the last image:

![image](https://user-images.githubusercontent.com/107324/89731619-5eb67780-da40-11ea-8b28-8ff55ec6034d.png)

But then I discovered something odd. If I then click the `+` button in the Image Optimizer menu, and select one single file, the newly selected image gets added to the queue, as well as the images that were not added while coming from Files. Also, something strange is happening with the filenames in the list. Once they are converted, their names are changed. NOt in Files, but well inside of Image Optimizer.

Here is a screen recording:

[image-optimizer-bug.mp4.zip](https://github.com/GijsGoudzwaard/Image-Optimizer/files/5047461/image-optimizer-bug.mp4.zip)

**Comment by GijsGoudzwaard** [comment]
I'm not using elementary anymore, so any help on this issue would be greatly appreciated!
