### ISSUE TITLE
Add your stripe key to appdata

### ISSUE THREAD

**Issue by danrabbit** [GijsGoudzwaard/Image-Optimizer#53]
In the new version of AppCenter Dashboard, we're no longer modifying your appdata before publishing, so you'll need to add your stripe key to appdata.xml to continue to monetize your app in elementary OS 6

For your convenience, your public stripe key is:
`<value key="x-appcenter-stripe">pk_live_40ePZY3ASKqIWzz0L5xbDSJf</value>`

**Comment by GijsGoudzwaard** [comment]
Fixed in 853a40e262b4fe701f7236122d6b9e1e38a18bc2
