### ISSUE TITLE
The close/maximise buttons are shown in white

### ISSUE THREAD

**Issue by tomaswarynyca** [GijsGoudzwaard/Image-Optimizer#59]
Cannot distinguish where the buttons are.

![image](https://user-images.githubusercontent.com/41587659/130058653-12b619dd-c887-4acb-a5dc-ea1f307f9419.png)

**Comment by GijsGoudzwaard** [comment]
What distribution are you using?

**Comment by tomaswarynyca** [comment]
> What distribution are you using?

Elementary OS 6

**Comment by GijsGoudzwaard** [comment]
API's must have changed then :thinking: this worked before Elementary OS 6

**Comment by cassidyjames** [comment]
@GijsGoudzwaard yeah, OS 6 has an entirely new stylesheet and some styling APIs may have changed as a result. Is the intended design that it's just a flat white window like before?

**Comment by GijsGoudzwaard** [comment]
@cassidyjames The intended design is as it is in the README: 
![image](https://user-images.githubusercontent.com/5947260/130280751-ecdf263e-d76e-4f3a-a0b0-3ec5021b4a50.png)

**Comment by GijsGoudzwaard** [comment]
Fixed in #61
