### ISSUE TITLE
Outdated Release on Flathub

### ISSUE THREAD

**Issue by rmeissn** [GijsGoudzwaard/Image-Optimizer#65]
Your latest release on GitHub is v0.1.22 from the 21. August 2021.
The latest release on Flathub is v0.1.17 from 16. December 2019.

Would it be possible to update the Flathub package to the latest release?
Furthermore, my flatpak system (Fedora 37) is complaining about outdated dependencies of Image-Optimizer:

```
Info: runtime org.freedesktop.Platform branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.github.gijsgoudzwaard.image-optimizer

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github.gijsgoudzwaard.image-optimizer

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github.gijsgoudzwaard.image-optimizer
```

**Comment by GijsGoudzwaard** [comment]
I currently can't test if updating the `org.freedesktop.Platform.*` dependancies would break anything. I've created a pull request https://github.com/flathub/com.github.gijsgoudzwaard.image-optimizer/pull/7 to at least update the app to the latest version in flathub. Any help checking if updating the `org.freedesktop.Platform.*` dependancies would break anything is much appreciated

**Comment by GijsGoudzwaard** [comment]
Proposed a change to the flathub config that should fix the warnings (https://github.com/flathub/com.github.gijsgoudzwaard.image-optimizer/pull/8). Could you test the app using this version making sure this change does not break anything? e.g. run this to install the proposed version of the app: `flatpak install --user https://dl.flathub.org/build-repo/640/com.github.gijsgoudzwaard.image-optimizer.flatpakref`

**Comment by rmeissn** [comment]
I've quickly tested the newly updated one on Fedora 37: throws no errors/warnings, compresses jpg and png images as expected.

**Comment by GijsGoudzwaard** [comment]
According to https://flathub.org/apps/details/com.github.gijsgoudzwaard.image-optimizer the app is updated now

**Comment by rmeissn** [comment]
Thank you very much =)
