### ISSUE TITLE
Snapcraft release

### ISSUE THREAD

**Issue by krille-chan** [GijsGoudzwaard/Image-Optimizer#66]
Hello, I did a successful packaging of Image Optimizer for the Snap-Store using Snapcraft. I was going to ask if you would like to have it in your repository directly and if you want to have the responsibility in the Store. If not I could keep maintaining it for sure. Actually it was only a test for me if I can package it some years ago but now I saw that it has nearly 1000 active installations so please let me now how we should handle this :-)

**Comment by GijsGoudzwaard** [comment]
It'd be great if you could add it to the snap-store! Could you link it here once completed so I can add it to the readme?

**Comment by GijsGoudzwaard** [comment]
Was this your release @krillefear https://snapcraft.io/image-optimizer?

**Comment by krillefear** [comment]
> Was this your release @krillefear https://snapcraft.io/image-optimizer?

That's correct :) It already works fine as far as I can see

**Comment by krillefear** [comment]
Currently I try to update it to the latest version

**Comment by GijsGoudzwaard** [comment]
@krille-chan Thank you for releasing the app on the snapstore, however could you transfer it to my account? Would be more convenient for me to be able to be in control of the release-cycle. This is my account https://snapcraft.io/publisher/gijs-g

**Comment by krille-chan** [comment]
Thank you so much. I've requested the transfer here: https://forum.snapcraft.io/t/transfer-image-optimizer-to-gijs-g/41540

**Comment by krille-chan** [comment]
@GijsGoudzwaard I need to invite you as a collaborator first and for this I need your email address of your ubuntu account, not your username. Can you tell me where I can find your email?

**Comment by GijsGoudzwaard** [comment]
@krille-chan gijs.goudzwaard@gmail.com

**Comment by krille-chan** [comment]
Thanks, You should have an invite

**Comment by GijsGoudzwaard** [comment]
Thanks, i've got acces now! Could you now transfer the ownership?

**Comment by krille-chan** [comment]
Transfer request is here: https://forum.snapcraft.io/t/transfer-image-optimizer-to-gijs-g/41540/2

**Comment by GijsGoudzwaard** [comment]
Ownership has been transfered, thanks!
