### ISSUE TITLE
Cannot compress multiple files without re-opening app

### ISSUE THREAD

**Issue by Smaloki** [GijsGoudzwaard/Image-Optimizer#8]
When Image-Optimizer has finished compressing a file and I try to drag&drop another image into the window, there is no visual feedback that it is actually being processed. The list will only ever show the first picture that was compressed, even though the app does appear to be working on additional images (the latter assumption is based on the fact that CPU usage indicates Image-Optimizer is active; sometimes, it also creates temporary copies visible in Files).

Screencast: https://webmshare.com/ZrgQd (since Github apparently won't accept video attachments).

**Comment by GijsGoudzwaard** [comment]
This option is currently not available but would make a nice feature. When dragging a new file into the tree view it does let the titlebar change of color, which should not happen.

**Comment by GijsGoudzwaard** [comment]
Moved the bug to a new issue #11

**Comment by alexgleason** [comment]
I agree. I wanted to add that in addition to letting the user drag in new files, it would also be great to have the "Browse files" button on this view as well to add new files that way. I like the single-click UI that elementary has, but it makes it harder to drag files, so I prefer browsing to them.

Thank you @GijsGoudzwaard for this really useful program! I didn't realize how much I wanted it until I had it.

**Comment by GijsGoudzwaard** [comment]
I will add this feature soon, also a "Browse files" button would make a nice addition. I'm currently wrapping up another project, once done I will work on a couple of issues from this project starting with this issue.

@alexgleason I'm glad you like it :)
